[project]
name = "ml-dvc-iris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc[gdrive]>=3.64.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "pyyaml",
    "joblib",
]
